language: cpp

compiler:
- gcc
#- clang

env:
  matrix:
    - SCONSFLAGS="opengl=False debug=False editor=False"
    - SCONSFLAGS="opengl=False debug=False editor=True"
    - SCONSFLAGS="opengl=False debug=True  editor=False"
    - SCONSFLAGS="opengl=False debug=True  editor=True"
    - SCONSFLAGS="opengl=True  debug=False editor=False"
    - SCONSFLAGS="opengl=True  debug=False editor=True"
    - SCONSFLAGS="opengl=True  debug=True  editor=False"
    - SCONSFLAGS="opengl=True  debug=True  editor=True"

before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -y libphysfs-dev libsdl1.2-dev libsdl-mixer1.2-dev
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.7; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.7"; fi

script: scons
