language: cpp

compiler:
- gcc
#- clang

env:
  global: SCONSFLAGS="d_debug=True e_editor=True s_opengl=False dxx=d+,e+,s+ builddir_prefix=build/"

before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -y libphysfs-dev libsdl1.2-dev libsdl-mixer1.2-dev
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.7; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.7"; fi

script: scons
